### ISSUE TITLE
Wifi disconnecting

### ISSUE THREAD

**Issue by fernandoiepe** [z2-dev/android_device_zuk_z2_plus#110]
It has been 1 month since the wifi disconnects and connects ... I realized this in the online games ... it is very fast but it is bothering ... I always use the latest releases ... thanks and sorry for google translator

**Comment by Luis-Gomez** [comment]
Good night,

The failure reported by @fernandoiepe I have suffered for some time, in this case I have it with Whatsapp Web, which marks me that it has been disconnected, and after a while reconnecting.

What logs do you need to know exactly what is happening?

Thanks in advance, for this great ROM for Lenovo ZUK Z2.

My baseband version is: M8996FAAAANAZM-1.70664.3.76387.1

-----------------------------------------------------------------------------------------------------------

Buenas noches,

El fallo que reporta @fernandoiepe lo llevo sufriendo ya un tiempo, en este caso yo lo tengo con Whatsapp Web, que me marca que se ha quedado sin conexion, y al rato se vuelve a reconectar.

¿Que logs te hacen falta para saber exactamente que esta ocurriendo?

Gracias de antemano, por esta gran ROM para Lenovo ZUK Z2.

Mi version de banda base es: M8996FAAAANAZM-1.70664.3.76387.1

**Comment by Luis-Gomez** [comment]
According to this website: https://zukfans.eu/community/threads/zuk-z2-baseband-collection-versions.4565/

The latest version of the baseband is: M8996FAAAANAZM-1.76387.1.92759.1

Do you recommend upgrading to that baseband version?

PD: Since the last update of 07-07-2017, the GPS has substantially improved, works just like the one of my previous cell phone a Motorola Moto G 2013

--------------------------------------------------------------------------------------------------------------

Segun esta web: https://zukfans.eu/community/threads/zuk-z2-baseband-collection-versions.4565/

La ultima version de la banda base es: M8996FAAAANAZM-1.76387.1.92759.1

¿Recomiendas actualizar a esa version de banda base?

PD: Desde la ultima actualizacion del 07-07-2017, el GPS a mejorado sustancialmente, funciona igual que el de mi anterior movil un Motorola Moto G 2013

**Comment by fernandoiepe** [comment]
https://www.reddit.com/r/PFSENSE/comments/5cyfuv/android_7_doesnt_work_until_i_disable_ipv6/

**Comment by Darkiu** [comment]
In the last revision the problem was solved.

**Comment by fernandoiepe** [comment]
Do you make all the wipes to install the latest version? Here continues the problem of wifi.

**Comment by Darkiu** [comment]
In this version 20170811 was resolved

**Comment by AlvaroBrey** [comment]
Then it's probably a wifi driver issue, but the drivers were reverted along with the kernel in version 20170822. 
When I publish a version with the new kernel again we'll see what happens.

**Comment by fernandoiepe** [comment]
The problem may be that I do not do all the wipes when I update

**Comment by Darkiu** [comment]
In this version 20170904 was resolved

**Comment by AlvaroBrey** [comment]
Perfect, closing then
