### ISSUE TITLE
Keyboard missing from decryption screen

### ISSUE THREAD

**Issue by AlvaroBrey** [z2-dev/android_device_zuk_z2_plus#20]
After reboot, decrypt screen shows up, but no keyboard appears, so the user can't input decrypt password.

Edit: phone doesn't hang during encryption

**Comment by luytens** [comment]
Had the same problem here.

**Comment by Mixxer5** [comment]
This is a longshot, but I've had this issue on other phone. Problem was caused by keyboard app, I fixed it by flashing google keyboard. It was long time ago (over a year) though and it might be something different.

**Comment by bugDoe** [comment]
I noticed few things:

- all TWRP version mess up the /data partition when you format it. This means TWRP forgets to reserve 16 KB of free space in the footer to allow the storing of encryption keys. To solve this you have to manually resize the ext4 data partition. 
On this link you can find how to do it manually, even though I couldn't find the reason why this is happening: https://dustri.org/b/cyanogen-reboot-without-encrypting-the-phone.html

I fix it by sending this command: mke2fs -T ext4 -L data /dev/block/mmcblk0p48 56770259

- all TWRP versions are not working (official and unofficial) with /data encrypted, they can't mount it. The only version that works perfectly is the TWRP 3.0.2 built by Fedor from 23/12/2016

- I don't know if it can help you but encryption works perfectly with Dirty Unicorns build of 19/02/2017 by davidevinavil, it doesn't work anymore on version of 15/03/2017 (maybe you can check changes in the source code)

- the problem seems bypassing last step of the encryption where the Android logo is shown with the progress bar running (the green robot is shown at the first reboot and after 3 reboots too, when error occurs only the first time reboot is shown).
When the problem occurs you can't enter PIN/password because no keyboard is shown and you can't use pattern method too because the touch input doesn't work even though the decryption of /data partition works when using TWRP 3.0.2 build by fedor. (with all type of locking methods)

Attached you can find a log. It is made with pattern security enabled, with working DU, I don't know how to enable logcat with locked device when using lineage!
[DU-19-02-2017.txt](https://github.com/ontherunvaro/android_device_zuk_z2_plus/files/852608/DU-19-02-2017.txt)

**Comment by bugDoe** [comment]
[lineage-nopattern.txt](https://github.com/ontherunvaro/android_device_zuk_z2_plus/files/852624/lineage-nopattern.txt)
this log is done with lineage and encryption enabled but no pattern/password/pin locked.
Hopefully this helps a bit. I really can't find any way to make a log after the phone crashes because there's no way for me to get the logcat.

**Comment by bugDoe** [comment]
Another update on this issue:
- as I've reported here: https://zukfans.eu/community/threads/7-1-x-z2-unofficial-dirty-unicorns-by-davidevinavil.4279/page-108#post-37047 on DU-rom the encryption was working perfectly on builds before 5th of March (so last build working is the 04/03/2017). I hope this can help you to fix the problem by checking the sources of DU. Seems like DU took sources/patches from you after 5th of March like many other ROM developers (all ROMs using your sources have this problem).
- I tried all other versions of Lineage OS and none of them is working with encryption enabled.

In the hoping these reports will help you to fix the bug if you need anything more just let me know.

**Comment by AlvaroBrey** [comment]
@bugDoe can you try with [this TWRP version](https://www.androidfilehost.com/?fid=673368273298939719)?

**Comment by bugDoe** [comment]
Yes I tried it. 
It doesn't work. I get the message "Process interrupted it's taking too long to decrypt data partition" or something similar. Seems like the decryption goes in timeout.

**Comment by Artemiis** [comment]
I also have this problem, no keyboard is showing up after succesful encryption. It's also with pattern or pin, so the problem might me somewhere else (anything dependent of /data)

In DU with adb shell i can unlock the /data partition with "vdc cryptfs checkpw <pw>" and then mount the block device to /data , but then i can not unlock because of: user unlocked but no home found (i searched long but didn't found a way to fix this)

Flashing an other keyboard didn't solve this problem, i tried with 3 different.

Logcat of DU boot with encryption without keyboard: 
[logcatencrypt.txt](https://github.com/ontherunvaro/android_device_zuk_z2_plus/files/867229/logcatencrypt.txt)

**Comment by bugDoe** [comment]
Could it be it's something related to selinux/sepolicy denials?
Seems like this is the different point where davidevinavil added on his sources and merged by your sources, commits made on Mar 3, 2017

Maybe I'm wrong, but this seems the only changes he did and after that no more working builds.

**Comment by AlvaroBrey** [comment]
@bugDoe No, those changes are irrelevant, and I can't find any relevant changes in Davide's kernel or vendor sources either.
I haven't had time to properly test it yet, but my current theory is that there were some changes on upstream android sources, and LineageOS just happened to merge them before DU though.
I need one bit of information from you though, if you use the february DU _now_, does encryption work?

**Comment by AlvaroBrey** [comment]
Oops, closed accidentally

**Comment by bugDoe** [comment]
Hello,

TWRP 3.0.2 Fedor917 23/12/2016 from here: https://yadi.sk/d/JWaxwHrj34c6RJ

DU_z2_plus_7.1.1_20170226-2329.v11.1-UNOFFICIAL.zip from here: https://www.androidfilehost.com/?fid=529152257862706333

I did these steps right now to be sure once again:
- Format Data in Wipe menu of TWRP
- wipe System with advanced button
- reboot to recovery
- start adb shell: "cat /proc/partitions" shows /dev/block/mmcblk0p48 is 56770275 length
- I set it shorter of 16 KB with this command after unmount of Data: "mke2fs -T ext4 -L data /dev/block/mmcblk0p48 56770259"
- launch command "sync"
- reboot to recovery
- flash DU of 26/02/2017 with TWRP's zip Install method (no other things flashed: no gapps, no supersu, no magisk)
- restart system
- first boot with DU
- set PIN code: 12345678
- enable encryption
- encryption process starts, device is automatically rebooted 3 times with encryption robot showing up the screen
- phone reboots with encryption enabled and showing PIN input box
- I insert the PIN and everything works perfectly
- I reboot to recovery and also TWRP can decrypt data

So... yes, everything is still working with a full wipe clean new flash of Febraury version.

**Comment by Artemiis** [comment]
Could it be something with odex? ( --> https://zukfans.eu/community/threads/7-1-x-z2-unofficial-dirty-unicorns-by-davidevinavil.4279/page-98#post-35395 )

@davidevinavil just to be informed this thread is talking about du...

In log theres:
`01-27 17:19:04.662   887   887 I PackageManager: /system/app/LatinIME changed; collecting certs
01-27 17:19:04.842   887   887 W PackageManager: Unknown permission android.permission.DOWNLOAD_WITHOUT_NOTIFICATION in package com.android.inputmethod.latin
01-27 17:19:04.901   574   574 D installd: Detected label change from u:object_r:system_data_file:s0 to u:object_r:app_data_file:s0:c512,c768 at /data/data/com.android.inputmethod.latin; running recursive restorecon
01-27 17:19:04.902   574   574 D installd: Detected label change from u:object_r:system_data_file:s0 to u:object_r:app_data_file:s0:c512,c768 at /data/user_de/0/com.android.inputmethod.latin; running recursive restorecon
01-27 17:19:04.902   574   574 E installd: Failed to mark default storage /data/data/com.android.inputmethod.latin: Operation not supported on transport endpoint
01-27 17:19:04.903   887   887 W PackageManager: Failed to migrate com.android.inputmethod.latin: Failed to execute migrate_app_data [null, com.android.inputmethod.latin, 0, 1]: -1
01-27 17:19:05.983   887   887 E InputMethodManagerService: Ignoring updateSystemUiLocked due to an invalid token. uid:1000 token:null
01-27 17:19:06.002   887   887 W InputMethodManagerService: Reset the default IME as "Resource" is ready here.
01-27 17:19:06.013   887   887 I InputMethodManagerService: Default found, using com.android.inputmethod.latin/.LatinIME
01-27 17:19:06.013   887   887 W InputMethodManagerService: Illegal subtype state: old subtype = null, new subtype = android.view.inputmethod.InputMethodSubtype@c9194f98
01-27 17:19:06.011   887   887 W system_server: type=1400 audit(0.0:16): avc: denied { setsched } for scontext=u:r:system_server:s0 tcontext=u:r:drmserver:s0 tclass=process permissive=0
01-27 17:19:06.011   887   887 W system_server: type=1400 audit(0.0:17): avc: denied { setsched } for scontext=u:r:system_server:s0 tcontext=u:r:keystore:s0 tclass=process permissive=0
01-27 17:19:06.011   887   887 W system_server: type=1400 audit(0.0:18): avc: denied { setsched } for scontext=u:r:system_server:s0 tcontext=u:r:mediacodec:s0 tclass=process permissive=0
01-27 17:19:06.011   887   887 W system_server: type=1400 audit(0.0:19): avc: denied { setsched } for scontext=u:r:system_server:s0 tcontext=u:r:mediadrmserver:s0 tclass=process permissive=0
01-27 17:19:06.011   887   887 W system_server: type=1400 audit(0.0:20): avc: denied { setsched } for scontext=u:r:system_server:s0 tcontext=u:r:mediaextractor:s0 tclass=process permissive=0
01-27 17:19:06.011   887   887 W system_server: type=1400 audit(0.0:21): avc: denied { setsched } for scontext=u:r:system_server:s0 tcontext=u:r:drmserver:s0 tclass=process permissive=0
01-27 17:19:06.011   887   887 W system_server: type=1400 audit(0.0:22): avc: denied { setsched } for scontext=u:r:system_server:s0 tcontext=u:r:mediacodec:s0 tclass=process permissive=0
01-27 17:19:06.011   887   887 W system_server: type=1400 audit(0.0:23): avc: denied { setsched } for scontext=u:r:system_server:s0 tcontext=u:r:mediaextractor:s0 tclass=process permissive=0
01-27 17:19:06.011   887   887 W system_server: type=1400 audit(0.0:24): avc: denied { setsched } for scontext=u:r:system_server:s0 tcontext=u:r:mediadrmserver:s0 tclass=process permissive=0
01-27 17:19:06.018   887   887 I Zygote  : Process: zygote socket opened, supported ABIS: arm64-v8a
01-27 17:19:06.029   887   887 I ActivityManager: Start proc 1533:com.android.inputmethod.latin/u0a8 for service com.android.inputmethod.latin/.LatinIME
01-27 17:19:06.029   887   887 V InputMethodManagerService: Adding window token: android.os.Binder@704a6a1`

`system@app@LatinIME@LatinIME.apk@classes.dex: Permission denied(13)
01-27 17:19:06.139  1533  1533 W art     : Failed execv(/system/bin/patchoat --instruction-set=arm64 --input-oat-file=/system/app/LatinIME/oat/arm64/LatinIME.odex --output-oat-file=/data/dalvik-cache/arm64/system@app@LatinIME@LatinIME.apk@classes.dex --patched-image-location=/system/framework/boot.art) because non-0 exit status`


EDIT: Also i have successfully upgraded to versions of du newer than 5th, this doesn't brick keyboard.
@ontherunvaro perhaps you do a test build with WITH_DEXPREOPT := true in BoardConfig.mk ?

**Comment by bugDoe** [comment]
I checked the LatinIME directory inside Febraury version and found that it has the "/system/app/LatinIME/oat/arm64/LatinIME.odex" file (asked by the command pointed by Artemiis).
This file is not there anymore on last March build.

I tried to search in XDA board and all I could found are many threads that are talking about the reinstallation of default keyboard.

So probably the problem is right there in the LatinIME apk (default AOSP keyboard)

**Comment by AlvaroBrey** [comment]
Thanks @bugDoe and @Artemiis, that narrows the search substantially.
In the meantime, I have compiled a TWRP build which _should_ have the correct partition size for `/data`. You can get it [here](https://www.androidfilehost.com/?fid=673368273298942449), and sources are [here](https://github.com/ontherunvaro/twrp_device_zuk_z2_plus). Hopefully it should simplify testing because we won't have to manually resize data.

**Comment by dmd79** [comment]
So deodex should be the problem with encryption?

**Comment by AlvaroBrey** [comment]
@davidevinavil worth giving a shot at least

**Comment by dmd79** [comment]
Building right now.. In an our will be available odex build

**Comment by dmd79** [comment]
@bugDoe this is DU odex if you can try let me know

https://mega.nz/#!Ow1hiLob!ooteqpGDOeC0LdA9Ge1ca-8THQ8r6vWcDeZ46yhLRa4

**Comment by dmd79** [comment]
You must clean install of course

**Comment by bugDoe** [comment]
@davidevinavil it works!! I can see PIN keyboard and phone decrypts correctly!

@ontherunvaro I tried your TWRP and doesn't work well: 
- I can't decrypt data partition
- "Format Data" button still wipes all the Data partition without reserving the 16 KB

**Comment by dmd79** [comment]
Ok, so the odex build is the solution of this decryption bug

**Comment by AlvaroBrey** [comment]
Currently testing odex in LOS, let's see what happens.
@bugDoe, after formatting data with my TWRP build, I could encrypt without any problem. Isn't it supposed to fail if there's no space for the crypto footer?
I can't seem to decrypt from TWRP though.

**Comment by AlvaroBrey** [comment]
Dexpreopt does not seem to solve the issue in LOS. The odex file is there but the keyboard still doesn't show up.
Anyway, @davidevinavil , using dexpreopt is not a valid solution in my opinion. We should instead find out why LatinIME is not getting odexed on the first boot (and in my case, some additional problems probably).

**Comment by bugDoe** [comment]
@ontherunvaro 
Using your TWRP build:
- cat /proc/partitions still shows 56770275 len for block mmcblk0p48 after I pressed the Format Data button (like all the other TWRP versions I tried)
- I tried to flash DU build linked by davidevinavil (which works with the resize command I wrote above) and tried it without the resize of the block by NOT reserving 16 KB ->  the encryption fails with a loop in ZUK logo (no DU logo shown). Maybe this is the reason why LOS odexed fails too. If you can upload a version for test I can try LOS odexed too.
Checking the log for encryption with LOS in past without reserving 16 KB I got NO encryption and normal boot without the loop facing now with DU but I could find in logcat the message "E/Cryptfs ( 1890): Orig filesystem overlaps crypto footer region.  Cannot encrypt in place."
I don't know why with your TRWP and DU I faced a boot loops after encryption, but I tried 4 times and I faced the same behaviour.
The only working way for now is by using odex build of DU and 16 KB reserved manually after a Data Format.

@davidevinavil 
In DU changing password/PIN/pattern in security menu doesn't change the boot/decryption password.

**Comment by AlvaroBrey** [comment]
@bugDoe understood, I will upload my odexed build in a while

**Comment by AlvaroBrey** [comment]
@bugDoe send me an email to varo@ontherunvaro.com or speak to me at @ontherunvaro on Telegram and I will give you the link.

**Comment by AlvaroBrey** [comment]
@bugDoe just to confirm: according to you, what is the correct number for the size of `data`? `56770259` ?

Edit: after running `mke2fs -T ext4 -L data /dev/block/mmcblk0p48 56770259; sync`, `cat /proc/partitions` still shows `56770275` for `mmcbk0p48`

Edit 2: Actually, now that I think of it, `cat /proc/partitions` should always show the same size. It's the filesystem what's being resized, _not_ the partition.

**Comment by bugDoe** [comment]
I talked with ontherunvaro and we found the followings:
- TWRP-25-03-2017 build by ontherunvaro works well with the "Format Data" button. It format the `/data` partition and reserving the needed 16 KB for the storing of encryption keys needed by the cryptfs filesystem.
- `cat /proc/partitions` always shows the length of the block, you need to use `df` tool to check the filesystem partition size, with this tool we could verify that the 16KB are actually reserved.
- LOS flashed with TWRP by ontherunvaro seems working with the encryption process, however still the PIN/password/pattern input is not possible (keyboard not shown); after a while you keep the phone on with the input box blinking the device reboots; after 10/15 minutes about something strange happens and the background image is shown with phone locked.
- TWRP build by ontherunvaro is not able to decrypt partition `/data` yet (partition can successfully decrypted with old 3.0.2 by Fedor917), no idea what's different because Fedor917 lost sources of old TWRP build.
- no idea why DU rebooted on old test with TWRP build by ontherunvaro, I tried again and everything worked now, maybe in the first test I did a mistake in one of the step-by-step.
- `/data` partition size is different between my device and ontherunvaro's one; we have a difference of almost 1 GB of free space, probably caused by different version of QFIL flashed stock ROM.

_Edit by repo owner: formatting_

**Comment by optimumpr** [comment]
It is not keyboard. The main culprit is that the framework_min restart fails to bring essential services, including keyguard/keyboard. System doesn't even see radio or simcard. It doesn't see dalvik, it doesn't see art. My suspicion is that encryption may be tied to bootloader, the same way as selinux is: if you disable selinux, the phone doesn't boot...

**Comment by rayzulnut** [comment]
Yep I am having the no keyboard at the enter pin screen to start Android screen. I leave it for about half an hour and after many reboots I find that after 15min I get my wallpaper with no icons followed by another reboot. I then wait another 15 to 20min and there it is a keyboard appears. I input my pin and phone is decrypted and boots into android. Takes over 30min to get that keyboard  though. I am using the latest Linage 14.1 ontherun build,  20170603. Just wanted to share my experience.

**Comment by optimumpr** [comment]
After you finally get the keyboard and the phone fully boots, do you have to go through the same process when you reboot? If it takes 30 minutes the first time only, one can live with it...

**Comment by rayzulnut** [comment]
Hi mate,

Yeah every time the phone reboots it takes around 30min for the keyboard to
popup. If it was only the one time we could live with that.
If I could supply you with any other info, please let me know but still
love your work on the Zuk Z2. 😀

Cheers

**Comment by Recursiivio** [comment]
I have used twrp-3.1.1-0-z2_plus.img (2017-05-18) from the start and it seems that this issue persists, I cannot encrypt my phone as it gets stuck in the way this issue oversees. 3 times over now, every time I encrypt from OS (be it lineage or RR), I get stuck on following boot.

I have been removing encryption within twrp by cancelling the decryption and formatting data. 

@ontherunvaro Can you please reupload your custom build (if that is still relevant today), the link is dead.

**Comment by AlvaroBrey** [comment]
@Recursiivio it isn't relevant anymore, encryption isn't a recovery issue.

**Comment by Recursiivio** [comment]
My bad, I was under the impression that the culprit was the erroneous partition creation by twrp on the zuk.

**Comment by NedelchevT** [comment]
Hi @optimumpro has fixed encryption here is the commit he shared https://github.com/ZUK2/android_device_zuk_z2_plus-1/commit/4924a2598d89ea268cf78583586da09071846aed if you haven't yet seen it ;)

**Comment by AlvaroBrey** [comment]
Thanks @NedelchevT, I had indeed seen it, but havent been able to test it
yet.

**Comment by AlvaroBrey** [comment]
@NedelchevT I have now had time to test it and I can confirm it does **not** fix the problem for us. The phone does exactly the same than before applying that commit.

**Comment by optimumpr** [comment]
@ontherunvaro 

That's because you need to build the entire rom, as opposed to kernel only. This commit has also fixed encryption for Candy rom, according to @miju12

**Comment by DD3Boh** [comment]
@optimumpr how could you think to build the kernel only if the edit is in the device tree?
 Anyway I talked with @miju12 and he said that yes, worked but:
He doesn't know if worked before
He is facing FCs of various apps like chrome and the simcard isn't recognised.

**Comment by optimumpr** [comment]
@DD3Boh 
I can think that because I know what I am talking about. Init.qcom.rc is pulled into boot.img during kernel build. Where did you think all rc files are? So, if you make changes in those, you don't always need to rebuild the entire rom. However, here you do, because vold binary is going to be built differently.

Crashing of various apps has nothing to do with encryption. It is prebuilt webview that needs to be updated. Just copy and paste from Lineage: this you know how to do... .

As far as whether he had it before: he uses the same device tree and nobody had encryption working before. Not since the beginning of February...

**Comment by AlvaroBrey** [comment]
@optimumpr I had already built the whole rom, not just kernel or any other part. It simply does not work for me :\

**Comment by optimumpr** [comment]
@ontherunvaro  OK. Have you looked at logcat? Try to set selinux permissive. 

What I can do is look at all rc files, including init.rc.  Maybe there were changes there too. But I doubt it. I remember that when the keyboard finally appeared right away for the first time and I entered the password, I still couldn't decrypt. Instead I would get a prompt: although your password is correct, data is corrupt, press factory reset. So, I had to revert all other commits to go to vanilla vold etc...

**Comment by miju12** [comment]
I use the commit mentioned above with a clean build and clean install,  encryption worked. But I have never tested it before. After rebooting sometimes it doesn't recognize my sim card and when I opened tuga browser and chrome force closes. Another reboot would fix the problems, sim card gets recognized and chrome etc work fine. To remove encryption in twrp I used wipe data it showed unable to mount data. After that I reboot and data partition was wiped. SELinux was permissive

**Comment by optimumpr** [comment]
@miju12 

To remove encryption, you must press the button on the right in wipe. Then you'll get a prompt to enter yes. Chrome and others: you either have to update prebuilt webview or install goggle webview. Simcard problems have to do with David pulling blobs from other devices without full verification. 

@ontherunvaro 
Try to odex your rom, as I have never tried encryption on deodexed rom.

**Comment by miju12** [comment]
@optimumpr the bug happens sometimes only when encryption is set. if it is not set everything works fine

**Comment by optimumpr** [comment]
@miju12 

Once the password is entered, the device restarts the same way as it would without encryption. And it is not happening on Jaguar. You should try to switch to varotone's device tree and blobs. I haven't updated any blobs since April and none of my users complain about signal or simcard problems. Signalwise, the phone worked fine in April. Why change anything, if it wasn't broken?

**Comment by AlvaroBrey** [comment]
Please keep the discussion related to encryption problems, otherwise I'm gonna start editing/deleting comments. This is not a forum.

**Comment by optimumpr** [comment]
All right. I give up... . Good luck to everybody....

**Comment by AlvaroBrey** [comment]
Encryption and decryption are working correctly from release 20170930
