### ISSUE TITLE
Changing the WLAN hotspot settings requires a reboot

### ISSUE THREAD

**Issue by 508279079** [z2-dev/android_device_zuk_z2_plus#54]
更改WLAN热点设置(如密码)，需要重启设置才会生效。
Change the WLAN hotspot settings (such as password), need to restart the settings will take effect.

(I reuse old issues, because they are what I have mistakenly added.)

**Comment by AlvaroBrey** [comment]
I've already told you this before: do ***not*** reuse old issues, even if you think you're doing the right thing. Notifications aren't the same and it's harder to keep track of things.

As for the actual issue: I can't reproduce it. To make settings effective I just need to turn the _wifi hotspot_ off and on, not the whole phone, and that's expected behaviour.

**Comment by 508279079** [comment]
我很抱歉，我不会再重新使用旧问题。你可以暂时关闭这个问题，待我测试出问题所在，再反馈。
I am sorry, I will not reuse old issues. You can close this issues. Wait for me to test out of the problem and then I will feedback.
