### ISSUE TITLE
doze error while compiling.

### ISSUE THREAD

**Issue by MRTHAKER** [z2-dev/android_device_zuk_z2_plus#76]
![image](https://cloud.githubusercontent.com/assets/25181187/25497948/ce4e6ac0-2ba3-11e7-971a-c9bd95add5dc.png)
 the error is in the picture doze folder always causing this error.

**Comment by AlvaroBrey** [comment]
Please provide a sufficient description of your error.

**Comment by MRTHAKER** [comment]
please have a look at the picture.

**Comment by AlvaroBrey** [comment]
Assuming you are building LineageOS, you are missing [packages/resources/devicesettings](https://github.com/LineageOS/android_packages_resources_devicesettings), just as that error says...
I get the feel you're *not* building LOS though, and my sources are for LOS only, you probably need to change things in order to build other ROMS.
Anyway, issues in this repo are meant for bugs in the ROM, not for dev help. For this you're better off joining #lineageos-dev or ##z2_plus-dev on irc.freenode.net

**Comment by MRTHAKER** [comment]
i tired with adding that you repo you told but still same error can you tell me what changes i have to for compiling non lineage roms.

**Comment by AlvaroBrey** [comment]
I only build LOS, so no, can't help you there. Good luck!

**Comment by MRTHAKER** [comment]
okay thanks for help bro but your tree is very stable and doze error is
solved by removing doze just users can't configure u-touch but that is not
a big issue.
