### ISSUE TITLE
OTA update is not working (build 20170526)

### ISSUE THREAD

**Issue by onderaldemir** [z2-dev/android_device_zuk_z2_plus#96]
check for updates but No updates available

***
*ISSUES ARE NOT A DISCUSSION/SUPPORT FORUM*. Comments irrelevant to the issue WILL be removed.

If this issue is to report a bug, please provide everything you can from the list below:
- ROM build version (date):20170526
- logcat (pastebin link):
- dmesg (pastebin link):
- console-ramoops (pastebin link):
- Steps to reproduce:

**Comment by AlvaroBrey** [comment]
You're the same guy of the previous "OTA not working" issue. Since you're the only one reporting this, I think it may be an issue on your part.
Are you using any kind of proxy or agressive firewall to access the Internet? Are you perhaps on a work or university public wifi?  Please try to think of any details that may affect your connectivity.

**Comment by AlvaroBrey** [comment]
No response from submitter.
